all : clean build test run
build : clean
	javac -d build -cp lib/junit-4.12.jar:lib/hamcrest-core-1.3.jar ./src/main/java/*.java ./src/test/java/*.java
test : clean build
	java -cp .:lib/junit-4.12.jar:lib/hamcrest-core-1.3.jar:build org.junit.runner.JUnitCore EdgeConnectorTest
run : clean build
	java -cp build RunEdgeConvert
clean :
	find . -name \*.class -exec rm {} \;
